
services:
  frontend:
    image: rakib3004/event-builder-frontend:latest
    container_name: event-builder-frontend
    ports:
      - "7010:7010"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    image: rakib3004/event-builder-backend:latest
    container_name: event-builder-backend
    ports:
      - "7020:7020"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_builder_db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - db
      - minio

  db:
    image: postgres:13
    container_name: event-builder-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_builder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: event-builder-minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data: